### ISSUE TITLE
Underline home explore and space is a little bit too high

### ISSUE THREAD

**Issue by huni2k1** [CharleneKwok/WeTravel#4]

**Comment by CharleneKwok** [comment]
Thanks I did that on purpose, part of my design

**Comment by huni2k1** [comment]
I can not load the home page while trying to run your app locally what configuration should I do?

**Comment by CharleneKwok** [comment]
Because I put the API key into the environmental variable and did not post
to GitHub just for safety reasons. So you cannot load the home page sorry
